### ISSUE TITLE
is it possible to toggle TODO, WORKING, DONE status

### ISSUE THREAD

**Issue by youngoo** [danielmagnussons/orgmode#45]

**Comment by defterGoose** [comment]
yes, I've been looking for an answer to this as well, cycling through these states is one of the most basic features of standard orgmode

**Comment by danielmagnussons** [comment]
There is a pull request for this, #71

**Comment by danielmagnussons** [comment]
Works now, thanks to https://github.com/danielmagnussons/orgmode/pull/71 and @martisak
