### ISSUE TITLE
integrated Markdown Syntax

### ISSUE THREAD

**Issue by oieusouofred** [danielmagnussons/orgmode#54]
Hi, I really wish I could integrate the **Markdown***syntax* with the orgmode, but I am pretty fresh at this stuff so I don't even know what to read or where to find a source to teach me how to do this. 

If someone could guide me I would do the hard work for sure!
I really like this plugging and I want to make it better!

**Comment by danielmagnussons** [comment]
Hi, there are multiple markdown plugins already and I'm not sure this feature has any value in  this plugin.
