### ISSUE TITLE
Restores folds to the wrong files

### ISSUE THREAD

**Issue by Michael-Klassen** [danielmagnussons/orgmode#68]
In `orgmode_store.py` the `OrgmodeStore` class doesn't work properly with folded code.

If you fold a section of a file then close that file, `OrgmodeStore` will save the folds.
If you then open a different file, `OrgmodeStore` will restore the folds to that different file.

The problem is caused by the fact that `OrgmodeStore` uses `get_view_index` as the key but (at least after you close a tab) `get_view_index` does not uniquely identify the file.

**Comment by danielmagnussons** [comment]
Fix in 0269d47e52c5e47bf57149c78887ab9cc33010c3 . Thanks for posting avery understandable bug report =)

**Comment by andremeireles** [comment]
@danielmagnussons - I installed the plugin yesterday and folded a javascript code and the fold persists.
This user have a similar issue: [https://github.com/danielmagnussons/orgmode/issues/74](https://github.com/danielmagnussons/orgmode/issues/74)
This user too: [Code is folded automatically on sublime start](https://forum.sublimetext.com/t/code-is-folded-automatically-on-sublime-start/42032)
