### ISSUE TITLE
Org mode org-schedule (C-c C-s) error

### ISSUE THREAD

**Issue by BuddhiLW** [danielmagnussons/orgmode#77]
### Expected behavior
I press C-c C-s and expected to prompt the calendar to chose a date.

### Actual behavior
But, actually, for a split second the calendar appears, and then emacs returns me the message:

version-to-list: Invalid version syntax: ‘’ (must start with a number)

### Steps to reproduce the problem
Create a TODO item, press C-c C-s on top of it.

### Environment & Version information
All my org related packages are up to date.

### Emacs version
GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3) of 2020-08-29

### Operating system
Artix Linux (Arch with runit et el.)

![pic-selected-210102-1025-56](https://user-images.githubusercontent.com/59554283/103458239-e00af100-4ce4-11eb-82f6-36e11c6cf5e9.png)

**Comment by BuddhiLW** [comment]
https://user-images.githubusercontent.com/59554283/103458396-4ba18e00-4ce6-11eb-81b8-4e79cf486f95.mp4

**Comment by MCSH** [comment]
I'm getting the exact same error, I'm not well versed with emacs debugging, if there are anythings I can provide, please let me know. This is the content of the Warnings buffer:

`Error (use-package): org-journal/:catch: Invalid version syntax: ‘’ (must start with a number)`

And this is the MEssages:

`version-to-list: Invalid version syntax: ‘’ (must start with a number)
`

**Comment by localauthor** [comment]
This error is described [here](https://github.com/bastibe/org-journal/issues/325#issuecomment-766171071) and [here](https://emacs.stackexchange.com/questions/62678/nov-mode-returns-binary-buffer-and-file-mode-specification-error-error-invali). Installing [org-mode 9.4.4 from Elpa](https://orgmode.org/elpa.html) and restarting Emacs resolved the issue for me.

**Comment by MCSH** [comment]
Thank you, that fixed the problem.
